In [83]:
import numpy as np
import nibabel as nb
from rois.roi_utils import find_nonzero_index
import matplotlib
from nilearn.plotting import plot_roi
from nilearn.image import new_img_like

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [91]:
def find_nonzero_index(array, axis, firstorlast='first'):
    if firstorlast not in ['first', 'last']:
        raise ValueError("Parameter 'firstorlast' must be either 'first' or 'last'.")

    mask = array != 0
    indices = np.where(mask)

    if firstorlast == 'first':
        if indices[axis].size > 0:
            return np.min(indices[axis])
        else:
            return None  # or any other indication for no non-zero elements
    else:  # for 'last'
        if indices[axis].size > 0:
            return np.max(indices[axis])
        else:
            return None

In [92]:
binary_vol = nb.load('../../../anat_roi_masks/wholebrain.nii').get_fdata()

In [104]:
find_nonzero_index(binary_vol, 1, firstorlast='last')

91

In [106]:
binary_vol[30:50,92,39]

memmap([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])

In [27]:
def first_nonzero(arr, axis, invalid_val=-1):
    mask = arr!=0
    return np.where(mask.any(axis=axis), mask.argmax(axis=axis), invalid_val)

In [50]:
mask = binary_vol != 0

In [64]:
mask = binary_vol > 1e-8

In [75]:
np.unique(binary_vol[binary_vol>1e-8])

array([1.])

In [70]:
mask.shape

(79, 95, 79)

In [65]:
np.unique(mask)

array([False,  True])

In [61]:
np.unique(np.argmax(mask, axis=1))

array([0])

In [ ]:
np.max()

In [89]:
np.min(np.where(np.argmax(mask, axis=1))[0])

4

In [90]:
np.max(np.where(np.argmax(mask, axis=1))[0])

74

In [49]:
binary_vol = nb.load('../../../anat_roi_masks/wholebrain.nii').get_fdata()

In [35]:
first_nonzero(binary_vol[:, 54, :], 0)

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [4]:
binary_vol = binary_vol != 0

In [6]:
max_along_axis = np.max(binary_vol, axis=1)

In [8]:
max_along_axis.shape

(79, 79)

In [9]:
indices = np.where(binary_vol)

In [10]:
indices

(array([ 5,  5,  5, ..., 73, 74, 74]),
 array([32, 32, 32, ..., 32, 32, 32]),
 array([29, 30, 31, ..., 33, 30, 31]))

In [12]:
axis = 1
last_nonzero_index = [idx[axis] for idx in zip(*indices) if max_along_axis[tuple(idx[i] for i in range(binary_vol.ndim) if i != axis)]][-1]

In [16]:
first_nonzero_index = [idx[axis] for idx in zip(*indices) if max_along_axis[tuple(idx[i] for i in range(binary_vol.ndim) if i != axis)]]

In [17]:
first_nonzero_index

[32,
 32,
 32,
 32,
 32,
 29,
 30,
 31,
 31,
 31,
 31,
 31,
 31,
 32,
 32,
 32,
 32,
 33,
 27,
 27,
 27,
 27,
 27,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 32,
 32,
 32,
 32,
 32,
 33,
 33,
 33,
 33,
 25,
 25,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 32,
 32,
 32,
 32,
 32,
 32,
 33,
 33,
 33,
 24,
 24,
 24,
 24,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
